[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]

# Solidity
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200

# Fuzzing
fuzz_runs = 512
max_test_rejects = 100000

via_ir = true
verbosity = 2

[profile.default.fuzz]
max_str_len = 32

[rpc_endpoints]
arc_testnet = "${RPC_URL}"
